export type UserRole = "coordinator" | "foster";

export type AnimalStatus =
	| "needs_foster"
	| "in_foster"
	| "adopted"
	| "medical_hold"
	| "in_shelter"
	| "transferring"; // Not yet in shelter, being transferred

export type IntakeType = "surrender" | "transfer" | string; // Primarily surrender/transfer, but allow custom
export type Sex = "male" | "female";
export type SpayNeuterStatus = "fixed" | "not_fixed";
export type LifeStage = "kitten" | "adult" | "senior";
export type FeLVFIVStatus = "negative" | "positive" | "pending" | "not_tested";
export type PlacementPriority = "high" | "normal";
export type PlacementRequestStatus =
	| "pending"
	| "approved"
	| "rejected"
	| "fulfilled"
	| "cancelled";

// Tags for filtering and categorization (can be expanded later)
export type AnimalTag =
	| "fine_with_dogs"
	| "fine_with_cats"
	| "bottle_fed"
	| "kid_friendly"
	| "not_kid_friendly"
	| "needs_socialization"
	| "special_needs"
	| string; // Allow custom tags

// Socialization level (range 0-5 or similar)
export type SocializationLevel = 0 | 1 | 2 | 3 | 4 | 5 | null; // null = unknown/not assessed

// Timestamped media for tracking when photos were added
export interface TimestampedPhoto {
	url: string; // File URL/path (from Supabase storage)
	uploaded_at: string; // ISO date string
	uploaded_by: string; // User ID (required)
}

export interface Animal {
	id: string;

	// Basic Info
	name?: string; // Optional - can be unnamed
	species: string; // Usually "cat" but keeping flexible
	// NOTE: primary_breed might change to tags later for better filtering
	primary_breed?: string; // Dropdown with custom input
	physical_characteristics?: string;
	sex?: Sex;
	spay_neuter_status?: SpayNeuterStatus;
	life_stage?: LifeStage;

	// Dates & Age (all stored as ISO date strings)
	intake_date?: string; // When animal came in/coming in (combines incoming/intake)
	date_of_birth?: string; // Rarely available
	age_estimate?: number; // Estimated age when DOB unknown
	date_available_for_adoption?: string;

	// Source & Placement
	source?: string; // Rescue name/source (renamed from 'from' - SQL reserved word)
	intake_type?: IntakeType;
	status: AnimalStatus;
	priority?: boolean; // High priority flag for urgent placement needs
	current_foster_id?: string; // ID of current foster (references User/Foster)

	// Medical (structured as string for now, can be split into tags/arrays later)
	medical_needs?: string; // Medical history, conditions, medications, special care
	vaccines?: string; // Could be array later, string for now
	felv_fiv_test?: FeLVFIVStatus;
	felv_fiv_test_date?: string; // When test was done or needed

	// Behavioral (structured as string for now, can be split into tags/arrays later)
	behavioral_needs?: string; // Behavioral notes, training needs, etc.
	socialization_level?: SocializationLevel; // 0-5 scale, null if unknown

	// Tags for filtering
	// NOTE: Stored as array for MVP. Could migrate to junction table (animal_tags) for better querying/filtering later
	tags?: AnimalTag[]; // e.g., "fine_with_dogs", "bottle_fed", "kid_friendly"

	// Relationships
	group_id?: string; // If part of a group
	parent_id?: string; // If has a parent (mom)
	// NOTE: Stored as array for MVP. Could migrate to junction table (animal_siblings) for more complex relationships later
	sibling_ids?: string[]; // Related animals

	// Petstablished Sync
	added_to_petstablished?: boolean;
	petstablished_sync_needed?: boolean; // Info needs updating
	petstablished_last_synced?: string;

	// Notes & Metadata
	additional_notes?: string;
	created_by?: string; // User ID who created
	created_at: string; // ISO date string
	updated_at: string; // ISO date string
}

export interface AnimalGroup {
	id: string;
	name?: string; // e.g., "Litter of 4 kittens"
	description?: string;
	// NOTE: Stored as JSONB array for MVP. Could migrate to separate photos table for better querying later
	group_photos?: TimestampedPhoto[]; // Timestamped group photos
	// NOTE: Stored as array for MVP. Could migrate to junction table (group_animals) if needed for more complex group management
	animal_ids: string[]; // Animals in this group
	current_foster_id?: string; // ID of current foster (if entire group is with one foster)
	created_at: string; // ISO date string
	updated_at: string; // ISO date string
}

export interface PlacementRequest {
	id: string;
	// Can be for single animal OR group
	animal_id?: string; // Single animal request
	group_id?: string; // Group placement request

	// Display info (may duplicate animal/group name for quick reference)
	name?: string; // Name(s) - e.g., "Fluffy" or "Litter of 4 kittens"
	description?: string; // Description of the placement opportunity and what's needed (medical needs, behavioral needs, etc.) might be autogenerated from other fields

	// Photos (timestamped)
	// NOTE: Stored as JSONB array for MVP. Could migrate to separate photos table for better querying later
	photos?: TimestampedPhoto[];

	// Placement-specific needs (may differ from animal's general needs)
	medical_needs?: string; // Medical needs for this specific placement
	behavioral_needs?: string; // Behavioral needs for this specific placement

	// Status & Priority
	status: PlacementRequestStatus;
	priority: PlacementPriority; // "high" or "normal" (combines urgency)

	// Additional placement details
	duration?: string; // How long foster needed
	location?: string; // "in shelter" or specific location

	// Metadata
	created_by?: string; // User ID who created
	created_at: string; // ISO date string
	updated_at: string; // ISO date string
}

// Base user fields shared by all users
interface BaseUser {
	id: string;
	email: string;
	full_name?: string;
	created_at: string; // ISO date string
	updated_at: string; // ISO date string
}

export interface Foster extends BaseUser {
	role: "foster";
	// Foster-specific fields
	experience_level?: string; // e.g., "experienced", "new", "bottle feeder"
	// NOTE: household_details might be extracted into tags later for better filtering
	household_details?: string; // Other pets, kids, allergies, etc.
	// NOTE: preferred_animal_profiles might be extracted into tags later for better filtering
	preferred_animal_profiles?: string; // What types of animals they prefer
	// NOTE: Simple boolean toggle for MVP. Might change to calendar with specific dates later
	availability?: boolean; // Simple toggle: available or not available
}

export interface Coordinator extends BaseUser {
	role: "coordinator";
	// Coordinator-specific fields can be added here if needed
}

// Union type for when you need to handle either role
export type User = Foster | Coordinator;

// Messaging types
export type ConversationType = "foster_chat" | "coordinator_group";

export interface Conversation {
	id: string;
	organization_id: string;
	type: ConversationType;
	foster_profile_id?: string;
	created_at: string;
	updated_at: string;
}

export interface Message {
	id: string;
	conversation_id: string;
	sender_id: string;
	content: string;
	created_at: string;
	edited_at?: string;
	photo_urls?: string[] | null; // Array of photo URLs from Supabase Storage
}
