export type UserRole = "coordinator" | "foster";

export type AnimalStatus =
	| "in_foster"
	| "adopted"
	| "medical_hold"
	| "in_shelter"
	| "transferring"; // Not yet in shelter, being transferred

// Combined sex and spay/neuter status type
export type SexSpayNeuterStatus =
	| "female"
	| "male"
	| "spayed_female"
	| "neutered_male";

export type LifeStage = "kitten" | "adult" | "senior" | "unknown";
export type FeLVFIVStatus = "negative" | "positive" | "pending" | "not_tested";
export type PlacementPriority = "high" | "normal";
export type PlacementRequestStatus =
	| "pending"
	| "approved"
	| "rejected"
	| "fulfilled"
	| "cancelled";

// Tags for filtering and categorization (can be expanded later)
export type AnimalTag =
	| "fine_with_dogs"
	| "fine_with_cats"
	| "bottle_fed"
	| "kid_friendly"
	| "not_kid_friendly"
	| "needs_socialization"
	| "special_needs"
	| string; // Allow custom tags

// Photo metadata for animals (minimal metadata for permission checks)
export interface PhotoMetadata {
	url: string; // Photo URL (required)
	uploaded_by?: string; // User/profile ID (optional, needed for permission checks - fosters can only delete their own photos)
}

// Timestamped media for tracking when photos were added
export interface TimestampedPhoto {
	url: string; // File URL/path (from Supabase storage)
	uploaded_at: string; // ISO date string
	uploaded_by: string; // User ID (required)
}

export interface Animal {
	id: string;

	// Basic Info
	name?: string; // Optional - can be unnamed
	species: string; // Usually "cat" but keeping flexible
	// NOTE: primary_breed might change to tags later for better filtering
	primary_breed?: string; // Dropdown with custom input
	physical_characteristics?: string;
	sex_spay_neuter_status?: SexSpayNeuterStatus; // Combined sex and spay/neuter status
	life_stage?: LifeStage;

	// Dates & Age (all stored as ISO date strings)
	date_of_birth?: string; // Rarely available
	age_estimate?: number; // Estimated age when DOB unknown

	// Placement
	status: AnimalStatus;
	display_placement_request?: boolean; // Control if animal appears on placement request page
	priority?: boolean; // High priority flag for urgent placement needs
	current_foster_id?: string; // ID of current foster (references User/Foster)

	// Medical (structured as string for now, can be split into tags/arrays later)
	medical_needs?: string; // Medical history, conditions, medications, special care

	// Behavioral (structured as string for now, can be split into tags/arrays later)
	behavioral_needs?: string; // Behavioral notes, training needs, etc.

	// Tags for filtering
	// NOTE: Stored as array for MVP. Could migrate to junction table (animal_tags) for better querying/filtering later
	tags?: AnimalTag[]; // e.g., "fine_with_dogs", "bottle_fed", "kid_friendly"

	// Relationships
	group_id?: string; // If part of a group

	// Photos (array of photo objects with minimal metadata)
	photos?: PhotoMetadata[]; // Array of photo objects with minimal metadata

	// Notes & Metadata
	additional_notes?: string;
	bio?: string; // Text field for animal biography - fosters will be able to edit
	created_by?: string; // User ID who created the animal
	created_at: string; // ISO date string
	updated_at: string; // ISO date string
}

export interface AnimalGroup {
	id: string;
	name?: string; // e.g., "Litter of 4 kittens"
	description?: string;
	priority?: boolean; // High priority flag for urgent placement needs
	// NOTE: Stored as JSONB array for MVP. Could migrate to separate photos table for better querying later
	group_photos?: TimestampedPhoto[]; // Timestamped group photos
	// NOTE: Stored as array for MVP. Could migrate to junction table (group_animals) if needed for more complex group management
	animal_ids: string[]; // Animals in this group
	current_foster_id?: string; // ID of current foster (if entire group is with one foster)
	created_at: string; // ISO date string
	updated_at: string; // ISO date string
}

export interface PlacementRequest {
	id: string;
	// Can be for single animal OR group
	animal_id?: string; // Single animal request
	group_id?: string; // Group placement request

	// Display info (may duplicate animal/group name for quick reference)
	name?: string; // Name(s) - e.g., "Fluffy" or "Litter of 4 kittens"
	description?: string; // Description of the placement opportunity and what's needed (medical needs, behavioral needs, etc.) might be autogenerated from other fields

	// Photos (timestamped)
	// NOTE: Stored as JSONB array for MVP. Could migrate to separate photos table for better querying later
	photos?: TimestampedPhoto[];

	// Placement-specific needs (may differ from animal's general needs)
	medical_needs?: string; // Medical needs for this specific placement
	behavioral_needs?: string; // Behavioral needs for this specific placement

	// Status & Priority
	status: PlacementRequestStatus;
	priority: PlacementPriority; // "high" or "normal" (combines urgency)

	// Additional placement details
	duration?: string; // How long foster needed
	location?: string; // "in shelter" or specific location

	// Metadata
	created_at: string; // ISO date string
	updated_at: string; // ISO date string
}

// Base user fields shared by all users
interface BaseUser {
	id: string;
	email: string;
	full_name?: string;
	created_at: string; // ISO date string
	updated_at: string; // ISO date string
}

export interface Foster extends BaseUser {
	role: "foster";
	// Foster-specific fields
	experience_level?: string; // e.g., "experienced", "new", "bottle feeder"
	// NOTE: household_details might be extracted into tags later for better filtering
	household_details?: string; // Other pets, kids, allergies, etc.
	// NOTE: preferred_animal_profiles might be extracted into tags later for better filtering
	preferred_animal_profiles?: string; // What types of animals they prefer
	// NOTE: Simple boolean toggle for MVP. Might change to calendar with specific dates later
	availability?: boolean; // Simple toggle: available or not available
	// Contact and inspection fields
	phone_number?: string; // Phone number for foster contact
	full_address?: string; // Full address for foster location
	home_inspection?: string; // Free-form text field for home inspection notes/information
}

export interface Coordinator extends BaseUser {
	role: "coordinator";
	// Coordinator-specific fields can be added here if needed
}

// Union type for when you need to handle either role
export type User = Foster | Coordinator;

// Messaging types
export type ConversationType = "foster_chat" | "coordinator_group";

export interface Conversation {
	id: string;
	organization_id: string;
	type: ConversationType;
	foster_profile_id?: string;
	created_at: string;
	updated_at: string;
}

export interface Message {
	id: string;
	conversation_id: string;
	sender_id: string;
	content: string;
	created_at: string;
	edited_at?: string;
	photo_urls?: string[] | null; // Array of photo URLs from Supabase Storage
}

// Message tag types
export type TagType = "animal" | "group" | "foster";

export const TAG_TYPES = {
	ANIMAL: "animal",
	GROUP: "group",
	FOSTER: "foster",
} as const;

export interface MessageTag {
	type: TagType;
	id: string;
	name: string;
}

// Raw message link data from Supabase (with joined data)
export interface MessageLinkRaw {
	id: string;
	message_id: string;
	animal_id: string | null;
	group_id: string | null;
	foster_profile_id: string | null;
	animals: { name: string } | null;
	animal_groups: { name: string } | null;
	profiles: { full_name: string } | null;
}

// Message with links from Supabase query (includes joined data)
// message_links is optional - can be omitted from queries when tagging is not in use
export type MessageWithLinks = {
	id: string;
	conversation_id: string;
	sender_id: string;
	content: string;
	created_at: string;
	edited_at: string | null;
	photo_urls: string[] | null;
	profiles: { full_name: string } | null;
	message_links?: Array<{
		id: string;
		animal_id: string | null;
		group_id: string | null;
		foster_profile_id: string | null;
		animals: { name: string } | null;
		animal_groups: { name: string } | null;
		profiles: { full_name: string } | null;
	}> | null;
};

// Message with metadata (sender name and tags) for UI
export type MessageWithMetadata = Message & {
	sender_name: string;
	tags: MessageTag[];
};
